# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "page_pool_alloc"
edition = "2021"
rust-version.workspace = true

[features]
vfio = ["user_driver/vfio"]

[dependencies]
hcl.workspace = true

user_driver.workspace = true
vm_topology.workspace = true
hvdef.workspace = true
sparse_mmap.workspace = true

inspect.workspace = true

parking_lot.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
memory_range.workspace = true

[lints]
workspace = true
